### ISSUE TITLE
Silence junk noise in tests

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#23]
Some of these are deprecation warnings and some are just debugging that is still active, probably across several gems.

Strangely, one is an outright error that doesn't result in a failed test, and several are seeming errors, also without failing a test.

```
rspec
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake/alt_system.rb:32:in `<module:AltSystem>': Use RbConfig instead of obsolete and deprecated Config.
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake/alt_system.rb:32:in `<module:AltSystem>': Use RbConfig instead of obsolete and deprecated Config.
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake.rb:960:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake.rb:962:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake.rb:965:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
/Users/atz/.rvm/gems/ruby-2.1.2/gems/rake-0.8.7/lib/rake.rb:966:in `<module:FileUtils>': Use RbConfig instead of obsolete and deprecated Config.
........................................................................................................................................................................................`raise_error` was called with non-proc object []
.........Cannot index druid:cj765pw7168.descMetadata: Unknown descMetadata namespace: nil
...........................................................................................................................................*....................Cannot index druid:ab123cd4567.descMetadata: Dor::Item#generate_dublin_core produced incorrect xml:
<?xml version="1.0"?>
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:srw_dc="info:srw/schema/1/dc-schema" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"/>

...Cannot index druid:ab123cd4567.descMetadata: Dor::Item#generate_dublin_core produced incorrect xml:
<?xml version="1.0"?>
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:srw_dc="info:srw/schema/1/dc-schema" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"/>

.Cannot index druid:ab123cd4567.descMetadata: Dor::Item#generate_dublin_core produced incorrect xml:
<?xml version="1.0"?>
<oai_dc:dc xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:srw_dc="info:srw/schema/1/dc-schema" xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd"/>

......You don't have tzinfo installed in your application. Please add it to your Gemfile and run bundle install
.................*..........Dor::RegistrationService.register_object failed to update solr index for druid:ab123cd4567: #<RestClient::ResourceNotFound: 404 Resource Not Found>
..Dor::RegistrationService.register_object failed to update solr index for druid:ab123cd4567: #<RestClient::ResourceNotFound: 404 Resource Not Found>
..Dor::RegistrationService.register_object failed to update solr index for druid:ab123cd4567: #<RestClient::ResourceNotFound: 404 Resource Not Found>
....../Users/atz/repos/dor-services/spec/fixtures/export/az871zd0000
........#<Moab::SignatureCatalog:0x007f969b83ff48 @entries=[], @signature_hash={}, @digital_object_id="druid:zz000zz0000", @version_id=0, @catalog_datetime=1969-12-31 16:00:00 -0800, @file_count=0, @byte_count=0, @block_count=0>
"<?xml version=\"1.0\"?>\n<signatureCatalog objectId=\"druid:zz000zz0000\" versionId=\"0\" catalogDatetime=\"1970-01-01T00:00:00Z\" fileCount=\"0\" byteCount=\"0\" blockCount=\"0\"/>\n"
...........................................
An error occurred in an after(:all) hook.
  NoMethodError: undefined method `each' for nil:NilClass
  occurred at /Users/atz/repos/dor-services/spec/dor/technical_metadata_service_spec.rb:54:in `block (2 levels) in <top (required)>'

.Applied remediation 'Signal foo 1' to 'foo'
Applied remediation 'Signal foo 2' to 'foo'
.Applied remediation 'Signal bar' to 'baz'
Applied remediation 'Signal baz' to 'baz'
.Applied remediation 'Signal bar' to 'baz'
Applied remediation 'Signal baz' to 'baz'
Applied remediation 'Signal foo 1' to 'foo'
Applied remediation 'Signal foo 2' to 'foo'
Applied remediation 'Signal bar' to 'bar'
.Applied remediation 'Signal bar' to 'bar'
```

**Comment by atz** [comment]
Partially quieted in revision to `5.0.0`, but still many left to catch.

**Comment by atz** [comment]
Calling this effectively done.
