### ISSUE TITLE
Spec file(s) fail when run individually

### ISSUE THREAD

**Issue by atz** [sul-dlss/dor-services#29]
The `publishable_spec` succeeds when run as part of `rspec`, but fails when run individually:

```rspec
$ rspec spec/dor/publishable_spec.rb 
.F........F....*.

Pending:
  Dor::Publishable#public_xml error handling throws an exception if any of the required datastreams are missing
    # No reason given
    # ./spec/dor/publishable_spec.rb:203

Failures:

  1) Dor::Publishable should provide a rightsMetadata datastream builder
     Failure/Error: expect(@item.datastreams['rightsMetadata'].ng_xml.to_s).not_to be_equivalent_to(rights_md)
     NoMethodError:
       undefined method `equivalent_to?' for #<String:0x007ff8eb0110f8>
     # ./spec/dor/publishable_spec.rb:69:in `block (2 levels) in <top (required)>'

  2) Dor::Publishable#public_xml produces xml with clones of the content of the other datastreams, keeping the originals in tact
     Failure/Error: expect(@item.datastreams['RELS-EXT'].content).to be_equivalent_to @rels
     NoMethodError:
       undefined method `equivalent_to?' for #<String:0x007ff8e8c95570>
     # ./spec/dor/publishable_spec.rb:125:in `block (4 levels) in <top (required)>'

Finished in 0.9696 seconds
17 examples, 2 failures, 1 pending

Failed examples:

rspec ./spec/dor/publishable_spec.rb:67 # Dor::Publishable should provide a rightsMetadata datastream builder
rspec ./spec/dor/publishable_spec.rb:121 # Dor::Publishable#public_xml produces xml with clones of the content of the other datastreams, keeping the originals in tact
```

**Comment by atz** [comment]
Fixed in dev
