### ISSUE TITLE
superclass mismatch for class Configuration

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#326]
```
TypeError: superclass mismatch for class Configuration
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-services-5.24.1/lib/dor/config.rb:6:in `<module:Dor>'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-services-5.24.1/lib/dor/config.rb:5:in `<top (required)>'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-services-5.24.1/lib/dor-services.rb:73:in `<module:Dor>'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/dor-services-5.24.1/lib/dor-services.rb:8:in `<top (required)>'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `block in require'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:240:in `load_dependency'
  /Users/jcoyne/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:274:in `require'
  /Users/jcoyne/workspace/dlss/hydrus/config/environment.rb:26:in `<top (required)>'
```

**Comment by jcoyne** [comment]
This was due to a monkeypatch in hydrus.
