### ISSUE TITLE
dor-services-app is calling deprecated methods

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/dor-services#397]
Find out why.  Perhaps we need to revert the deprecation.
```
DEPRECATION WARNING: thumb is deprecated and will be removed from dor-services version 7.0.0. (called from encoded_thumb at /home/travis/.rvm/gems/ruby-2.5.3/gems/dor-services-6.0.1/lib/dor/models/concerns/publishable.rb:23) (1 times); e.g.: 
    /home/travis/.rvm/gems/ruby-2.5.3/gems/dor-services-6.0.1/lib/dor/models/concerns/publishable.rb:23:in `encoded_thumb'
    /home/travis/build/sul-dlss/dor-services-app/app/models/dor/service_item.rb:60:in `thumb'
    /home/travis/build/sul-dlss/dor-services-app/spec/dor/service_item_spec.rb:216:in `block (3 levels) in <top (required)>'
    /home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `instance_exec'
    /home/travis/.rvm/gems/ruby-2.5.3/gems/rspec-core-3.8.0/lib/rspec/core/example.rb:254:in `block in run'
```

**Comment by jcoyne** [comment]
Looks like it'll just need to switch to `ERB::Util.url_encode(Dor::ThumbnailService.new(obj).thumb)` or similar.
